FROM node:18

WORKDIR /usr/src/app

COPY package.json ./
RUN npm install

COPY . .

CMD [ "node", "hello.js"]

# docker build -t my-node-app . (BUILD CONTAINER)
# docker run --rm my-node-app (RUN CONTAINER)